// Generated by gencpp from file crazy_ros/NumpyArrayFloat64.msg
// DO NOT EDIT!


#ifndef CRAZY_ROS_MESSAGE_NUMPYARRAYFLOAT64_H
#define CRAZY_ROS_MESSAGE_NUMPYARRAYFLOAT64_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crazy_ros
{
template <class ContainerAllocator>
struct NumpyArrayFloat64_
{
  typedef NumpyArrayFloat64_<ContainerAllocator> Type;

  NumpyArrayFloat64_()
    : data()  {
    }
  NumpyArrayFloat64_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> const> ConstPtr;

}; // struct NumpyArrayFloat64_

typedef ::crazy_ros::NumpyArrayFloat64_<std::allocator<void> > NumpyArrayFloat64;

typedef boost::shared_ptr< ::crazy_ros::NumpyArrayFloat64 > NumpyArrayFloat64Ptr;
typedef boost::shared_ptr< ::crazy_ros::NumpyArrayFloat64 const> NumpyArrayFloat64ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crazy_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'crazy_ros': ['/home/daniel/Documents/Crazyflie/crazyflie_project/ROS/crazyflie_ws/src/crazy_ros/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazy_ros/NumpyArrayFloat64";
  }

  static const char* value(const ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n\
";
  }

  static const char* value(const ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct NumpyArrayFloat64_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazy_ros::NumpyArrayFloat64_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZY_ROS_MESSAGE_NUMPYARRAYFLOAT64_H
